#!/bin/sh

################################################################################
# VAULT-SSH                                                                    #
################################################################################
# 2017-03 by Mike Okner <michael.okner@monsanto.com>
#
# SSH to a remote host using a signed key from Vault's CA.
# Simply wraps the `ssh` command, fetching a signed key before executing.
#
# Usage:
#    vault-ssh -i ~/.ssh/some_privatekey user@host
#

# Ensure VAULT_ADDR is set
if [ -z "$VAULT_ADDR" ]; then
  VAULT_ADDR='https://vault.agro.services'
fi

# Ensure Vault auth is current (Thanks @blord1)
vault token lookup > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Enter your Monsanto password to authenticate with Vault"
  read -s -p 'Password (will be hidden): ' PW
  echo ''
  vault login -method=userpass -path=ping username=$USER password="$PW"
  unset PW
fi

# Get the path to the key that will be used for this connection
KEYFILE=`ssh -G $@ | grep -i -m1 IdentityFile | awk '{print $2}' | sed "s|~|$HOME|"`
if [ -z "$KEYFILE" ]; then
    echo "Failed to determine which key to have Vault sign."
    exit 1
fi

# Get the role from the user's config
VAULT_ROLE=`cat ~/.vault_ssh_role 2>/dev/null`
if [ -z "$VAULT_ROLE" ]; then
    VAULT_ROLE='monuser'
fi

# Get a signed key from Vault
SIGNED=`vault write --field signed_key ssh/sign/$VAULT_ROLE public_key=@$KEYFILE.pub`
if [ -z "$SIGNED" ]; then
    echo "Error getting signed key from Vault for public key $KEYFILE.pub"
    exit 1
fi

# Write signed key to appropriate file
echo "$SIGNED" > $KEYFILE-cert.pub
chmod 0600 $KEYFILE-cert.pub

# Execute the original SSH command
ssh $@
